### ISSUE TITLE
Images won't load

### ISSUE THREAD

**Issue by Glavic** [titpetric/pendulum#2] opened 2017-09-08 13:20 UTC
When using `![](https://scene-si.org/post/2017-09-02-parsing-strings-with-go/heading.jpg)` in the editor image is not loaded.

Problem probably is that you are doing request to:
`http://10.0.0.139:8080/contents//https://scene-si.org/post/2017-09-02-parsing-strings-with-go/heading.jpg` ?

**Comment by titpetric** [comment] 2017-09-08 15:59
Thanks for the report, I have fixed this issue in the latest version.

1. I ignore http/https links from url rewriting now,
2. I serve the image based on the post filename and it's parent folder.

The second thing is hugo-specific. The way I have hugo set up is that the image will be loaded from a subfolder, which shares the post stub. So if you have `post-stub.md` and `![](heading.jpg)` it will attempt to load `/post-stub/heading.jpg` before trying `/heading.jpg`. It should improve the previews overall.

I also added specific support for `{% asset_img url "caption" %}` (hugo shortcode).

Let me know if it works for you now :)

**Comment by onedrawingperday** [comment] 2017-11-27 00:39
> The way I have hugo set up is that the image will be loaded from a subfolder, which shares the post stub. 

Can you please share your asset_img Hugo shortcode?

**Comment by titpetric** [comment] 2017-11-27 12:14
The issue is not considered open anymore, closing. Consult hugo docs for asset_img formatting.

**Closed as completed by titpetric** 2017-11-27 12:14 UTC

**Comment by onedrawingperday** [comment] 2017-11-27 14:03
I'm sorry @titpetric  I didn't make myself clear. 

I asked you to share your Hugo shortcode not because I'm clueless, but because your example above `{% asset_img url "caption" %}` has syntax errors that will cause Hugo errors.

The first problem is that you have used single curly brackets whereas Hugo's syntax for shortcodes requires double curly brackets. 

And the second problem is that you have entered  the img URL without quotes in the shortcode. This approach will always throw an unexpected character error, since non alphanumeric characters MUST be in quotes when used in shortcode params. See [this comment ](https://discourse.gohugo.io/t/youtube-shortcode-problem-when-the-id-contains-underscore--/8730/4?u=onedrawingperday)by Hugo's maintainer 

So that's why I asked you to share your shortcode.

PS
If I change your shortcode and put quotes in the URL like so: `{{% asset_img "1.jpg" %}}` the image preview will not load in Pendulum. Without the quotes the preview loads. But now that's not very practical because when the site is generated in Hugo the shortcode will be broken with the unquoted URL.

**Comment by titpetric** [comment] 2017-11-27 16:56
That would be a [hexo short code](https://hexo.io/docs/asset-folders.html), my error. Hugo I believe just uses standard markdown. Sorry for the confusion.

**Comment by onedrawingperday** [comment] 2017-11-27 17:35
Hugo uses both Blackfriday markdown as well as shortcodes. 

Thank you for Pendulum!
